---
apiVersion: v1
kind: Service
metadata:
  name: pz-server
  labels:
    app: pz-server
spec:
  ports:
    - port: 16261
      name: game-server
      protocol: UDP
      targetPort: 16261
    - port: 8766
      name: game-server-2
      protocol: UDP
      targetPort: 8766
  type: NodePort
  selector:
    app: pz-server